use_frameworks!

target 'ObjCPhoenixClient_Example' do
  pod 'ObjCPhoenixClient', :path => '../'
  
  pod 'YYModel', '~> 1.0.4'
  pod 'SDWebImage', '~> 4.4.0'
  pod 'Masonry', '~> 1.1.0'
  pod 'IQKeyboardManager', '~> 6.0.3'
  pod 'BlocksKit', '~> 2.2.5'
  pod 'SVProgressHUD', '~> 2.2.5'

end
